### ISSUE TITLE
Silo doesn't compile on macOS

### ISSUE THREAD

**Issue by henryleberre** [LLNL/Silo#224]
## Issue

Whenever we compile Silo on a Mac (x86 or M1), we get the following error message:
```
silo_hdf5.c:2173:5: error: implicit declaration of function 'zfp_init_zfp' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
```

Silo used to work for us on Mac with [this brew recipe](https://github.com/brewsci/homebrew-science/blob/master/Formula/silo.rb). It also appears that any previous version of Silo doesn't compile either with a similar error message pertaining to implicit declarations, although it doesn't mention ZFP.

## Reproduction

Here is how we compile Silo:
``` 
./configure --prefix=<install location> --enable-pythonmodule --enable-optimization    \
            --disable-hzip --disable-fpzip --enableportable-binary                     \
            FC=mpif90 F77=mpif77                                                       \
            -with-hdf5=<path to hdf5 /include>,<path to hdf5 /lib>                     \
            --disable-silex 

make -j <num_threads>
make install
```

We used version 4.11 downloaded from https://wci.llnl.gov/simulation/computer-codes/silo under the "Legacy Licensed Source Code" column header.

Any help would be greatly appreciated!

**Comment by henryleberre** [comment]
From [INSTALL](https://github.com/LLNL/Silo/blob/main/INSTALL):
```
   You can give `configure' initial values for configuration parameters
by setting variables in the command line or in the environment.  Here
is an example:

     ./configure CC=c89 CFLAGS=-O2 LIBS=-lposix

   *Note Defining Variables::, for more details.
```

Notice C89 is used. According to this [Stack Overflow post](https://stackoverflow.com/questions/17508503/is-implicit-function-declaration-legal-in-c89), implicit delcaration is legal in C89, but not in C99.

I'm not closing this issue yet because I still haven't gotten it to fully compile with HDF5.

**Comment by markcmiller86** [comment]
Not ignoring you...just off this whole week. Will follow up next week.

**Comment by henryleberre** [comment]
Thank you for responding, and have a nice break!

For future reference, we got the farthest in the build process with this configure call:

```
./configure CC=$(which gcc-11) CFLAGS="-std=gnu89 -O2" CXX=$(which g++-11)  \
            --prefix=$(pwd) --enable-pythonmodule --enable-optimization     \
            --disable-hzip --disable-fpzip FC=mpif90 F77=mpif77             \
            --with-hdf5=$(pwd)/../HDF5/hdf5/include,$(pwd)/../HDF5/hdf5/lib \
            --disable-silex
```

We specifically target gcc-11 since gcc on Mac points to a version of GCC using LLVM / Apple Clang, which ./configure dislikes. It still doesn't build fully but we are much closer than before.

**Comment by henryleberre** [comment]
Update: We are now also having issues on Linux. I have had the same on macOS but had to patch the file myself, adding quite a few `;` manually in  `H5FDsilo.c` to go any further in the compilation process. Are we doing anything wrong?

Files:
- [SILO's config.log](https://github.com/LLNL/Silo/files/7605862/config.log)
- [./configure & make output](https://github.com/LLNL/Silo/files/7605870/SILO.log)

Reproduction:
- Ubuntu v21.10.
- Silo v4.11 from https://wci.llnl.gov/sites/wci/files/2021-09/silo-4.11.tgz.
- `mpicc` -> `gcc` v11.2.0.
- `mpicxx` -> `g++` v11.2.0.
```
./configure --prefix=... --enable-pythonmodule --enable-optimization \
            --disable-hzip      --disable-fpzip                      \
            FC=mpif90 F77=mpif77 CC=mpicc CXX=mpicxx                 \
            --with-hdf5=...,...                                      \
            --disable-silex
make -j $(nproc)
make install prefix=...
```

First Error:
```
H5FDsilo.c: In function ‘file_write’:
H5FDsilo.c:256:1: error: expected ‘;’ before ‘}’ token
  256 | }
      | ^
H5FDsilo.c:848:9: note: in expansion of macro ‘H5E_PUSH_HELPER’
  848 |         H5E_PUSH_HELPER (func, H5E_ERR_CLS, H5E_IO, H5E_OVERFLOW, "addr undefined", -1, -1)
      |         ^~~~~~~~~~~~~~~
H5FDsilo.c:256:1: error: expected ‘;’ before ‘}’ token
  256 | }
      | ^
H5FDsilo.c:850:9: note: in expansion of macro ‘H5E_PUSH_HELPER’
  850 |         H5E_PUSH_HELPER (func, H5E_ERR_CLS, H5E_IO, H5E_OVERFLOW, "addr overflow", -1, -1)
      |         ^~~~~~~~~~~~~~~
```

**Comment by markcmiller86** [comment]
Sorry for what appears to be many dup's of the above comment!!! Darn chrome browser doesn't react well with GitHub. It kept telling me the comment couldn't be posted.

**Comment by markcmiller86** [comment]
The second problem you are reporting is due to [this change](https://github.com/HDFGroup/hdf5/blob/820695a78e3a277daea1bdcbb8ad54b8ee6650a5/release_docs/RELEASE.txt#L488) in HDF5. Silo is not yet compatible with that newest version of HDF5.

**Comment by markcmiller86** [comment]
As an aside, there are a few issues I see with your configuration....

* Did you really mean to specify the 1989 (30+ year old) standard? Maybe that was a typo and you meant `gnu98`? Either way, that is a very old standard and if for some reason Silo doesn't compile to that old standard, I can't justify trying to correct for it.
* Why are you compiling a *serial* library with a *parallel* compiler? Silo doesn't have any MPI dependence and so I am just curious what is driving you to compile with with the MPI compiler wrappers? Just to maintain compatability with other things you are building?
* I don't have access to newest compilers (gcc-11.2) and so cannot test some of the behavior you report.

I have an update correcting what I could here but you'll have to back off HDF5-1.12.1 or patch `H5FDsilo.c` yourself (the patch is easy) to correct. I'll close this when I commit that update. Thanks for the reports! 😉

**Comment by henryleberre** [comment]
@markcmiller86 Thank you very much for investigating our problems! I truly appreciate it. 

Mac support has been an issue for many of our users and I'm happy we are getting a fix for them! Since I'm working on a new code base, I initially tried to update some of our packages to see if it would help. I'll definitely revert to a compatible build of HDF5.

As for the issues you pointed out:
- When I was trying to fix the implicit declaration error, I found an example in [INSTALL]() where you set `CC=c89`. A Google search revealed that C89, interestingly enough, wouldn't treat this issue as an error! I then tried to use it. Should the following line be updated? https://github.com/LLNL/Silo/blob/014c31a9421b36f77c8798a3fa8357b1de3b1d2e/INSTALL#L81
- Using a parallel compiler is definitely an error! This code is embedded in a script that builds many codes requiring such compilers so it was most certainly a copy-paste error. Thanks!

Thank you once more.

**Comment by henryleberre** [comment]
Correction: We compile HDF5 with `--enable-parallel` and Silo didn't find HDF5 if we used "regular" compilers. Interestingly enough, `mpicc` and `mpicxx` are just fancy wrappers over those "regular" ones with the correct arguments to link to MPI.

On my system:
```
$ mpicc --showme
gcc -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -L/usr/lib/x86_64-linux-gnu/openmpi/lib -lmpi
```

**Comment by markcmiller86** [comment]
@henryleberre I did fix the HDF5-1.12.1 compilation issue in [this commit](1120cc918090328d65a6d362df66c5105bc552a2) which will be merged to the release candidate (RC branch) and to main shortly.

**Comment by markcmiller86** [comment]
@henryleberre I have investigated the issue you've reported when if HDF5 1.12.0 is installed with `--enable-parallel`, then Silo fails to *find* it if *regular* compilers (instead of MPI compiler wrappers used to compile HDF5) are used.

I am not sure entirely how best to fix this but the problem you are having is that the HDF5 library you are trying to use with Silo has a dependence on MPI. Silo's attempts to find HDF5 are spoiled due to missing `-L<path-to-MPI-install-dir>` and `-lmpi`. In other words, nothing can link to HDF5 library without also specifying how to link with MPI. Silo's configure script attempts to confirm not only that it can find `hdf5.h` but also that it can compile and run an executable that calls `H5open()`. Either or both of these steps can fail if HDF5 is installed with `--enable-parallel` and you neglect to inform Silo's configure of this.

Here is what I wound up having to do in this case...

I was using an MPI installed with VisIt...

```
[scratlantis:~/silo/4.11RC] miller86% /Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/bin/mpicc -show
clang -fexceptions -O2 -I/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/include \
-L/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/lib \
-lmpi -lpmpi
```

This tells me I need to set `LDFLAGS` to `-L/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/lib`, LIBS to `-lmpi -lpmpi` and CPPFLAGS to `-I/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/include` before calling Silo's configure. So, here is the command I used...

```
env LDFLAGS=-L/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/lib \
LIBS="-lmpi -lpmpi" \
CPPFLAGS=-I/Users/miller86/visit/third_party/3.2.0/mpich/3.3.1/i386-apple-darwin18_clang/include \
CC=clang CXX=clang++ ../configure --prefix=`pwd`/myinstall --enable-pythonmodule --enable-optimization \
--disable-hzip --disable-fpzip \
-with-hdf5=/Users/miller86/silo/hdf5-1.12.0/build_parallel/myinstall/include,/Users/miller86/silo/hdf5-1.12.0/build_parallel/myinstall/lib \
--disable-silex
```

and then Silo's configure will find HDF5 fine and everything will compile and run fine.

I have discovered some unnecessary MPI symbols that get used in Silo whenever it thinks it is linking to an MPI-enabled (e.g. `--enable-parallel` build) HDF5 that I have [removed](https://github.com/LLNL/Silo/pull/227/commits/8051bccb349564cf8ba54e3e45ae6f101437d167) due to this investigation. That should keep this a little cleaner.

All that said, I can't easily fix [this problem](https://github.com/LLNL/Silo/issues/224#issuecomment-982286125) and I believe the only solution is to adjust how you configure Silo as described above.

**Comment by henryleberre** [comment]
> All that said, I can't easily fix this problem and I believe the only solution is to adjust how you configure Silo as described above.

@markcmiller86 I think this is a perfectly reasonable workaround. I had also discovered in `config.log` that it tried to build a test program that failed because of lack of MPI.

Thank you once more for investigating diligently this issue!

**Comment by markcmiller86** [comment]
Resolved in 

* 4c0fe9c3bbf95125c294318ddbc9a122b34e20d3 (4.11RC)
* 3bd0ad60035f24b3e92a9549e4127c86fba8625c (main)

**Comment by rhaas80** [comment]
This still happens to me with silo-4.11. looking at the current C code in https://github.com/LLNL/Silo/blob/d6745d2f200472d65d18f6f9f8076f706c32ef22/src/hdf5_drv/H5FDsilo.c#L262 and the HDF5's commit https://github.com/HDFGroup/hdf5/pull/380 that requires a semicolon after H5Epush_ret I am not surprised by this (should affect all HDF5 starting 1.13: https://github.com/HDFGroup/hdf5/blob/e4fb9aa96ef805e2dada8a78c32aab8cf8c34f4a/release_docs/HISTORY-1_13.txt#L2133 ). 

A simple fix may be to add the missing semicolon and this may (I have not tested) work with both old and new HDF5 versions.

**Comment by markcmiller86** [comment]
The macro `H5EPR_SEMICOLON` should resolve to `;` for HDF5 version >= 1.10.8 I think.

**Comment by rhaas80** [comment]
Right, this is fixed in main (sorry I did not notice H5EPR\_SEMICOLON) but not in the latest release (4.11), at least:  
  
\`\`\`  
git checkout 4.11  
git grep H5EPR\_SEMICOLON  
\`\`\`

return nothing (it's in branch 4.11RC though).  I will wait of the next release I guess.
